### ISSUE TITLE
Failed to Read Image when api.SetImage(image) occurs after cv2.imshow()

### ISSUE THREAD

**Issue by AbelTan13** [sirfz/tesserocr#117]
Hi,

I noticed a strange and random bug:

I am using tesserocr with openCV2 python to read text in images.

Here is my image (labels2.bmp)

[(https://ibb.co/gmQAAT)]

Here is my code:

```


coords=[(34,46,280,292),(64,76,57,69),
        
        (41,53,16,28),

(185,197,196,210),

(221,233,50,69),

(144,156,50,69),

(216,228,23,35),

(387,406,291,313),

(195,212,287,309),

(137,187,184,215),

(137,149,23,35),

(224,243,180,202),

(104,116,23,35),(144,156,46,58)]

import cv2
path="labels2.bmp"
PIL_im= image = Image.open(path)
api1=PyTessBaseAPI()
api10=PyTessBaseAPI(psm=10)
width=PIL_im.size[0]
height=PIL_im.size[1]
img=image.copy()
img=cv2.imread(path)
for x,x2,y,y2 in coords:

 x,x2= f.min_x,f.max_x
 y,y2= f.min_y,f.max_y
 cv2.rectangle(img,(f.min_x,f.min_y),(f.max_x,f.max_y),(255,0,255),1)
 #cv.imshow("rect",img)
 #cv.waitKey(0)
 crop= PIL_im.crop((max(x-10,0),(max(y-10,0)),min(x2+10,width-1),min(y2+10,height-1)))
 api1.SetImage(crop)
 api1.Recognize()
 tex = api1.GetUTF8Text()
 #tex=tesserocr.image_to_text(crop)
 tex=tex.strip( ' ')
 if(len(tex)==0):
     api10.SetImage(crop)
     api10.Recognize()
     tex = api10.GetUTF8Text()
 print(x,x2,y,y2,tex)

```

Running this code was fine. however, when I uncomment cv.imshow and cv.waitKey(0),

```

coords=[(34,46,280,292),(64,76,57,69),
        
        (41,53,16,28),

(185,197,196,210),

(221,233,50,69),

(144,156,50,69),

(216,228,23,35),

(387,406,291,313),

(195,212,287,309),

(137,187,184,215),

(137,149,23,35),

(224,243,180,202),

(104,116,23,35),(144,156,46,58)]

import cv2
path="labels2.bmp"
PIL_im= image = Image.open(path)
api1=PyTessBaseAPI()
api10=PyTessBaseAPI(psm=10)
width=PIL_im.size[0]
height=PIL_im.size[1]
img=image.copy()
img=cv2.imread(path)
for x,x2,y,y2 in coords:

 x,x2= f.min_x,f.max_x
 y,y2= f.min_y,f.max_y
 cv2.rectangle(img,(f.min_x,f.min_y),(f.max_x,f.max_y),(255,0,255),1)
 cv.imshow("rect",img)
 cv.waitKey(0)
 crop= PIL_im.crop((max(x-10,0),(max(y-10,0)),min(x2+10,width-1),min(y2+10,height-1)))
 api1.SetImage(crop)
 api1.Recognize()
 tex = api1.GetUTF8Text()
 #tex=tesserocr.image_to_text(crop)
 tex=tex.strip( ' ')
 if(len(tex)==0):
     api10.SetImage(crop)
     api10.Recognize()
     tex = api10.GetUTF8Text()
 print(x,x2,y,y2,tex)
```

The console threw error 

  File "tesserocr.pyx", line 1552, in tesserocr._tesserocr.PyTessBaseAPI.SetImage

RuntimeError: Error reading image

How do I fix this bug?

**Comment by AbelTan13** [comment]
Hi,

It appears that the error also occurs when I send it a longer list.

The error occurs at random points.

Output of print(i,(x,x2,y,y2)) after 3 tries
``1 (94, 123, 50, 69)
2 (227, 243, 25, 46)
3 (235, 253, 46, 69)
4 (235, 253, 46, 69)
5 (246, 264, 27, 46)
6 (387, 406, 291, 313)
7 (387, 406, 291, 313)
8 (195, 212, 287, 309)
9 (195, 212, 292, 309)
10 (224, 243, 180, 202)
11 (155, 178, 196, 215)
12 (147, 164, 196, 215)
13 (137, 155, 193, 215)
14 (169, 187, 184, 206)
15 (333, 356, 254, 273)
16 (325, 342, 254, 273)
17 (315, 333, 251, 273)
18 (383, 402, 74, 96)
19 (200, 217, 71, 93)
20 (200, 217, 76, 93)
21 (187, 208, 71, 93)
22 (287, 305, 50, 69)
23 (287, 305, 50, 69)
24 (274, 291, 50, 69)
25 (265, 282, 50, 69)
26 (258, 274, 50, 69)
27 (249, 266, 50, 69)
28 (225, 243, 50, 69)
29 (178, 201, 50, 69)
30 (170, 187, 50, 69)
31 (148, 164, 50, 69)
32 (106, 123, 50, 69)
33 (94, 111, 50, 69)
34 (87, 103, 50, 69)
35 (55, 72, 50, 69)
36 (43, 60, 50, 69)
37 (36, 52, 50, 69)
38 (24, 41, 50, 69)
39 (339, 358, 47, 69)
40 (339, 358, 47, 69)
41 (328, 347, 47, 69)
42 (319, 336, 47, 69)
43 (319, 336, 52, 69)
44 (306, 327, 47, 69)
45 (213, 229, 47, 69)
46 (193, 211, 47, 69)
47 (160, 178, 47, 69)
48 (131, 148, 47, 69)
49 (131, 148, 52, 69)
50 (118, 139, 47, 69)
51 (73, 92, 47, 69)
52 (296, 312, 46, 69)
53 (235, 253, 46, 69)
54 (236, 252, 50, 69)
55 (387, 404, 27, 46)
56 (363, 381, 27, 46)
57 (354, 371, 27, 46)
58 (341, 358, 27, 46)
59 (328, 346, 27, 49)
60 (318, 336, 27, 46)
61 (309, 326, 27, 46)
62 (295, 312, 27, 46)
63 (286, 303, 27, 46)
64 (280, 295, 27, 46)
65 (266, 283, 27, 46)
66 (246, 264, 27, 46)
67 (246, 264, 27, 46)
68 (234, 250, 27, 46)
69 (220, 236, 27, 46)
70 (208, 224, 27, 46)
71 (198, 216, 27, 46)
72 (188, 206, 27, 46)
73 (188, 206, 27, 46)
74 (180, 197, 27, 46)
75 (167, 184, 27, 46)
76 (160, 176, 27, 46)
77 (150, 168, 27, 46)
78 (141, 159, 27, 49)
79 (118, 136, 27, 49)
80 (108, 126, 27, 46)
81 (89, 112, 27, 46)
82 (80, 98, 27, 46)
83 (80, 98, 27, 46)
84 (62, 80, 27, 46)
85 (62, 80, 27, 46)
86 (43, 60, 27, 46)
87 (302, 318, 25, 46)
88 (227, 243, 25, 46)
89 (23, 42, 24, 46)
90 (373, 391, 23, 46)
91 (374, 390, 27, 46)
92 (255, 271, 23, 46)
93 (130, 146, 23, 46)
94 (55, 71, 23, 46)
95 (34, 51, 23, 46)
96 (387, 406, 291, 313)
97 (195, 212, 287, 309)
98 (147, 178, 196, 215)
99 (137, 178, 193, 215)
100 (137, 187, 184, 215)
101 (325, 356, 254, 273)
102 (315, 356, 251, 273)
103 (200, 217, 71, 93)
104 (187, 217, 71, 93)
105 (287, 305, 50, 69)
106 (265, 291, 50, 69)
107 (249, 274, 50, 69)
108 (213, 243, 47, 69)
109 (170, 201, 50, 69)
110 (148, 178, 47, 69)
111 (94, 123, 50, 69)
112 (73, 103, 47, 69)
113 (43, 72, 50, 69)
114 (24, 52, 50, 69)
115 (339, 358, 47, 69)
116 (319, 347, 47, 69)
117 (306, 336, 47, 69)
118 (170, 211, 47, 69)
119 (131, 148, 47, 69)
120 (118, 139, 27, 69)
121 (296, 326, 27, 69)
122 (235, 253, 46, 69)
Traceback (most recent call last):

  File "<ipython-input-32-fce7d051c861>", line 1, in <module>
    runfile('C:/Users/Tan/Anaconda3/math project/example parse/Circle_Parser/pre_process.py', wdir='C:/Users/Tan/Anaconda3/math project/example parse/Circle_Parser')

  File "C:\Users\Tan\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\Tan\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Tan/Anaconda3/math project/example parse/Circle_Parser/pre_process.py", line 439, in <module>
    api1.SetImage(crop)

  File "tesserocr.pyx", line 1552, in tesserocr._tesserocr.PyTessBaseAPI.SetImage

RuntimeError: Error reading image




runfile('C:/Users/Tan/Anaconda3/math project/example parse/Circle_Parser/pre_process.py', wdir='C:/Users/Tan/Anaconda3/math project/example parse/Circle_Parser')
1 (94, 123, 50, 69)
2 (227, 243, 25, 46)
3 (235, 253, 46, 69)
4 (235, 253, 46, 69)
5 (246, 264, 27, 46)
6 (387, 406, 291, 313)
7 (387, 406, 291, 313)
8 (195, 212, 287, 309)
9 (195, 212, 292, 309)
10 (224, 243, 180, 202)
11 (155, 178, 196, 215)
12 (147, 164, 196, 215)
13 (137, 155, 193, 215)
14 (169, 187, 184, 206)
15 (333, 356, 254, 273)
16 (325, 342, 254, 273)
17 (315, 333, 251, 273)
18 (383, 402, 74, 96)
19 (200, 217, 71, 93)
20 (200, 217, 76, 93)
21 (187, 208, 71, 93)
22 (287, 305, 50, 69)
23 (287, 305, 50, 69)
24 (274, 291, 50, 69)
25 (265, 282, 50, 69)
26 (258, 274, 50, 69)
27 (249, 266, 50, 69)
28 (225, 243, 50, 69)
29 (178, 201, 50, 69)
30 (170, 187, 50, 69)
31 (148, 164, 50, 69)
32 (106, 123, 50, 69)
33 (94, 111, 50, 69)
34 (87, 103, 50, 69)
35 (55, 72, 50, 69)
36 (43, 60, 50, 69)
37 (36, 52, 50, 69)
38 (24, 41, 50, 69)
39 (339, 358, 47, 69)
40 (339, 358, 47, 69)
41 (328, 347, 47, 69)
42 (319, 336, 47, 69)
43 (319, 336, 52, 69)
44 (306, 327, 47, 69)
45 (213, 229, 47, 69)
46 (193, 211, 47, 69)
47 (160, 178, 47, 69)
48 (131, 148, 47, 69)
49 (131, 148, 52, 69)
50 (118, 139, 47, 69)
51 (73, 92, 47, 69)
52 (296, 312, 46, 69)
53 (235, 253, 46, 69)
54 (236, 252, 50, 69)
55 (387, 404, 27, 46)
56 (363, 381, 27, 46)
57 (354, 371, 27, 46)
58 (341, 358, 27, 46)
59 (328, 346, 27, 49)
60 (318, 336, 27, 46)
61 (309, 326, 27, 46)
62 (295, 312, 27, 46)
Traceback (most recent call last):

  File "<ipython-input-33-fce7d051c861>", line 1, in <module>
    runfile('C:/Users/Tan/Anaconda3/math project/example parse/Circle_Parser/pre_process.py', wdir='C:/Users/Tan/Anaconda3/math project/example parse/Circle_Parser')

  File "C:\Users\Tan\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\Tan\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Tan/Anaconda3/math project/example parse/Circle_Parser/pre_process.py", line 439, in <module>
    api1.SetImage(crop)

  File "tesserocr.pyx", line 1552, in tesserocr._tesserocr.PyTessBaseAPI.SetImage

RuntimeError: Error reading image




runfile('C:/Users/Tan/Anaconda3/math project/example parse/Circle_Parser/pre_process.py', wdir='C:/Users/Tan/Anaconda3/math project/example parse/Circle_Parser')
1 (94, 123, 50, 69)
2 (227, 243, 25, 46)
3 (235, 253, 46, 69)
4 (235, 253, 46, 69)
5 (246, 264, 27, 46)
6 (387, 406, 291, 313)
7 (387, 406, 291, 313)
8 (195, 212, 287, 309)
9 (195, 212, 292, 309)
10 (224, 243, 180, 202)
11 (155, 178, 196, 215)
12 (147, 164, 196, 215)
13 (137, 155, 193, 215)
14 (169, 187, 184, 206)
15 (333, 356, 254, 273)
16 (325, 342, 254, 273)
17 (315, 333, 251, 273)
18 (383, 402, 74, 96)
19 (200, 217, 71, 93)
20 (200, 217, 76, 93)
21 (187, 208, 71, 93)
22 (287, 305, 50, 69)
23 (287, 305, 50, 69)
24 (274, 291, 50, 69)
25 (265, 282, 50, 69)
26 (258, 274, 50, 69)
27 (249, 266, 50, 69)
28 (225, 243, 50, 69)
29 (178, 201, 50, 69)
30 (170, 187, 50, 69)
31 (148, 164, 50, 69)
32 (106, 123, 50, 69)
33 (94, 111, 50, 69)
34 (87, 103, 50, 69)
35 (55, 72, 50, 69)
36 (43, 60, 50, 69)
37 (36, 52, 50, 69)
38 (24, 41, 50, 69)
39 (339, 358, 47, 69)
40 (339, 358, 47, 69)
41 (328, 347, 47, 69)
42 (319, 336, 47, 69)
43 (319, 336, 52, 69)
44 (306, 327, 47, 69)
45 (213, 229, 47, 69)
46 (193, 211, 47, 69)
47 (160, 178, 47, 69)
48 (131, 148, 47, 69)
49 (131, 148, 52, 69)
50 (118, 139, 47, 69)
51 (73, 92, 47, 69)
52 (296, 312, 46, 69)
53 (235, 253, 46, 69)
54 (236, 252, 50, 69)
55 (387, 404, 27, 46)
56 (363, 381, 27, 46)
57 (354, 371, 27, 46)
58 (341, 358, 27, 46)
59 (328, 346, 27, 49)
60 (318, 336, 27, 46)
61 (309, 326, 27, 46)
Traceback (most recent call last):

  File "<ipython-input-34-fce7d051c861>", line 1, in <module>
    runfile('C:/Users/Tan/Anaconda3/math project/example parse/Circle_Parser/pre_process.py', wdir='C:/Users/Tan/Anaconda3/math project/example parse/Circle_Parser')

  File "C:\Users\Tan\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\Tan\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Tan/Anaconda3/math project/example parse/Circle_Parser/pre_process.py", line 439, in <module>
    api1.SetImage(crop)

  File "tesserocr.pyx", line 1552, in tesserocr._tesserocr.PyTessBaseAPI.SetImage

RuntimeError: Error reading image
``
