### ISSUE TITLE
Add recipe for conda-forge channel

### ISSUE THREAD

**Issue by Chilipp** [sirfz/tesserocr#196]
Hello @sirfz!

I wonder if there are any plans on creating a recipe for tesserocr on the community-based conda-forge channel for anaconda (https://conda-forge.org). With the tesseract library being available for Linux, OS X and Windows (see https://anaconda.org/conda-forge/tesseract), this would provide the perfect platform to distibute this fantastic package.

Are there any interests in this? I already made a conda recipe a few months ago that integrates well with the tesseract version 4.0.0 from conda-forge (see https://anaconda.org/chilipp/tesserocr, at that time tesseract was only available for linux and osx) and I would be willing to setup the basis for a tesserocr-feedstock on conda-forge (of course with adding you as maintainer). Once this initial setup is sorted out, the maintenance of the feedstock on conda-forge should be pretty straight-forward. What do you think?

**Comment by sirfz** [comment]
Hi @Chilipp,

I'm not a Conda user myself but of course I'd like to have tesserocr easily available for all platforms via Conda. Your contribution to this is very much welcome!

**Comment by Chilipp** [comment]
Alright! I will do this within the next days.

**Comment by chamoulox** [comment]
Hello @Chilipp 
Any news about adding tesserocr in conda-forge ? I was looking for tesserocr 2.4.1 in conda but there is only 2.4.0 right now

**Comment by Chilipp** [comment]
Hey @chamoulox! Sorry, for the delay! I started with (https://github.com/Chilipp/staged-recipes/commit/d84bcba028f911b012e5bd9695d00cfe08965a5e) it and should be able to create the PR for [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes) later today. I just want to test the build prior to making the PR on our linux, OS X and Windows servers.

**Comment by chamoulox** [comment]
Oh nice ! thanks a lot !

**Comment by Chilipp** [comment]
The recipe in https://github.com/Chilipp/staged-recipes/tree/master/recipes/tesserocr works well for linux and osx and I uploaded the builds for python 2.7, 3.6 and 3.7 to my personal anaconda channel. So you can already install it with

```
conda install -c chilipp -c conda-forge tesserocr
```

I am having build issues on Windows though because the build fails with `error: command 'cl.exe' failed: No such file or directory` (see details below). But I did not yet look into it very much. Nevertheless, I think this should be solved prior to creating the PR. Personally I am not a Windows user so any suggestions are highly welcomed!

<details>
<summary>Windows build error</summary>

```
(%BUILD_PREFIX%) %SRC_DIR%>python -m pip install . --no-deps --ignore-installed -vvv
Ignoring indexes: https://pypi.org/simple
Created temporary directory: C:\Users\PSommer\AppData\Local\Temp\pip-ephem-wheel-cache-7naww250
Created temporary directory: C:\Users\PSommer\AppData\Local\Temp\pip-req-tracker-9296ru7z
Created requirements tracker 'C:\\Users\\PSommer\\AppData\\Local\\Temp\\pip-req-tracker-9296ru7z'
Created temporary directory: C:\Users\PSommer\AppData\Local\Temp\pip-install-xpn5ywk9
Processing d:\phds\philipp_sommer\miniconda3\conda-bld\tesserocr_1570090822206\work
  Created temporary directory: C:\Users\PSommer\AppData\Local\Temp\pip-req-build-f335sbkh
  Added file:///D:/PhDs/Philipp_Sommer/Miniconda3/conda-bld/tesserocr_1570090822206/work to build tracker 'C:\\Users\\PSommer\\AppData\\Local\\Temp\\pip-req-tracker-9296ru7z'
    Running setup.py (path:C:\Users\PSommer\AppData\Local\Temp\pip-req-build-f335sbkh\setup.py) egg_info for package from file:///D:/PhDs/Philipp_Sommer/Miniconda3/conda-bld/tesserocr_1570090822206/wo
rk
    Running command python setup.py egg_info
    Supporting tesseract v4.1.0
    Building with configs: {'libraries': ['tesseract', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 67174400}}
    running egg_info
    creating pip-egg-info\tesserocr.egg-info
    writing pip-egg-info\tesserocr.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\tesserocr.egg-info\dependency_links.txt
    writing top-level names to pip-egg-info\tesserocr.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\tesserocr.egg-info\SOURCES.txt'
    Compiling tesserocr.pyx because it changed.
    [1/1] Cythonizing tesserocr.pyx
    reading manifest file 'pip-egg-info\tesserocr.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    D:\PhDs\Philipp_Sommer\Miniconda3\conda-bld\tesserocr_1570090822206\_h_env\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now
(Py2). This will change in a later release! File: C:\Users\PSommer\AppData\Local\Temp\pip-req-build-f335sbkh\tesserocr.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    warning: no previously-included files found matching '*.so'
    writing manifest file 'pip-egg-info\tesserocr.egg-info\SOURCES.txt'
  Source in c:\users\psommer\appdata\local\temp\pip-req-build-f335sbkh has version 2.4.1, which satisfies requirement tesserocr==2.4.1 from file:///D:/PhDs/Philipp_Sommer/Miniconda3/conda-bld/tesseroc
r_1570090822206/work
  Removed tesserocr==2.4.1 from file:///D:/PhDs/Philipp_Sommer/Miniconda3/conda-bld/tesserocr_1570090822206/work from build tracker 'C:\\Users\\PSommer\\AppData\\Local\\Temp\\pip-req-tracker-9296ru7z'

Building wheels for collected packages: tesserocr
  Created temporary directory: C:\Users\PSommer\AppData\Local\Temp\pip-wheel-nafuh2c_
  Building wheel for tesserocr (setup.py): started
  Destination directory: C:\Users\PSommer\AppData\Local\Temp\pip-wheel-nafuh2c_
  Running command 'D:\PhDs\Philipp_Sommer\Miniconda3\conda-bld\tesserocr_1570090822206\_h_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PSommer\\AppData\\Local
\\Temp\\pip-req-build-f335sbkh\\setup.py'"'"'; __file__='"'"'C:\\Users\\PSommer\\AppData\\Local\\Temp\\pip-req-build-f335sbkh\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.
read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\PSommer\AppData\Local\Temp\pip-wheel-nafuh2c_' --python-tag cp37
  Supporting tesseract v4.1.0
  Building with configs: {'libraries': ['tesseract', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 67174400}}
  running bdist_wheel
  running build
  running build_ext
  building 'tesserocr' extension
  creating build
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\PhDs\Philipp_Sommer\Miniconda3\conda-bld\tesserocr_1570090822206\_h_env\include -ID:\PhDs\Philipp_Sommer\Miniconda3\conda-bld\tesserocr_1570090822206\
_h_env\include -ID:\PhDs\Philipp_Sommer\Miniconda3\conda-bld\tesserocr_1570090822206\_h_env\Library\include -ID:\PhDs\Philipp_Sommer\Miniconda3\conda-bld\tesserocr_1570090822206\_h_env\Library\include
 /EHsc /Tptesserocr.cpp /Fobuild\temp.win-amd64-3.7\Release\tesserocr.obj -std=c++11 -DUSE_STD_NAMESPACE
  error: command 'cl.exe' failed: No such file or directory
  Building wheel for tesserocr (setup.py): finished with status 'error'
  ERROR: Failed building wheel for tesserocr
  Running setup.py clean for tesserocr
  Running command 'D:\PhDs\Philipp_Sommer\Miniconda3\conda-bld\tesserocr_1570090822206\_h_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PSommer\\AppData\\Local
\\Temp\\pip-req-build-f335sbkh\\setup.py'"'"'; __file__='"'"'C:\\Users\\PSommer\\AppData\\Local\\Temp\\pip-req-build-f335sbkh\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.
read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  Supporting tesseract v4.1.0
  Building with configs: {'libraries': ['tesseract', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 67174400}}
  running clean
  removing 'build\temp.win-amd64-3.7' (and everything under it)
  'build\lib.win-amd64-3.7' does not exist -- can't clean it
  'build\bdist.win-amd64' does not exist -- can't clean it
  'build\scripts-3.7' does not exist -- can't clean it
  removing 'build'
Failed to build tesserocr
Installing collected packages: tesserocr
  Created temporary directory: C:\Users\PSommer\AppData\Local\Temp\pip-record-kxt509_m
  Running setup.py install for tesserocr: started
    Running command 'D:\PhDs\Philipp_Sommer\Miniconda3\conda-bld\tesserocr_1570090822206\_h_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PSommer\\AppData\\Loc
al\\Temp\\pip-req-build-f335sbkh\\setup.py'"'"'; __file__='"'"'C:\\Users\\PSommer\\AppData\\Local\\Temp\\pip-req-build-f335sbkh\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=
f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PSommer\AppData\Local\Temp\pip-record-kxt509_m\install-record.txt' --
single-version-externally-managed --compile
    Supporting tesseract v4.1.0
    Building with configs: {'libraries': ['tesseract', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 67174400}}
    running install
    running build
    running build_ext
    building 'tesserocr' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\PhDs\Philipp_Sommer\Miniconda3\conda-bld\tesserocr_1570090822206\_h_env\include -ID:\PhDs\Philipp_Sommer\Miniconda3\conda-bld\tesserocr_157009082220
6\_h_env\include -ID:\PhDs\Philipp_Sommer\Miniconda3\conda-bld\tesserocr_1570090822206\_h_env\Library\include -ID:\PhDs\Philipp_Sommer\Miniconda3\conda-bld\tesserocr_1570090822206\_h_env\Library\inclu
de /EHsc /Tptesserocr.cpp /Fobuild\temp.win-amd64-3.7\Release\tesserocr.obj -std=c++11 -DUSE_STD_NAMESPACE
    error: command 'cl.exe' failed: No such file or directory
  Running setup.py install for tesserocr: finished with status 'error'
Cleaning up...
  Removing source in C:\Users\PSommer\AppData\Local\Temp\pip-req-build-f335sbkh
Removed build tracker 'C:\\Users\\PSommer\\AppData\\Local\\Temp\\pip-req-tracker-9296ru7z'
ERROR: Command errored out with exit status 1: 'D:\PhDs\Philipp_Sommer\Miniconda3\conda-bld\tesserocr_1570090822206\_h_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\U
sers\\PSommer\\AppData\\Local\\Temp\\pip-req-build-f335sbkh\\setup.py'"'"'; __file__='"'"'C:\\Users\\PSommer\\AppData\\Local\\Temp\\pip-req-build-f335sbkh\\setup.py'"'"';f=getattr(tokenize, '"'"'open'
"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PSommer\AppData\Local\Temp\pip-record-kxt5
09_m\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "%PREFIX%\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in main
    status = self.run(options, args)
  File "%PREFIX%\lib\site-packages\pip\_internal\commands\install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "%PREFIX%\lib\site-packages\pip\_internal\req\__init__.py", line 58, in install_given_reqs
    **kwargs
  File "%PREFIX%\lib\site-packages\pip\_internal\req\req_install.py", line 959, in install
    spinner=spinner,
  File "%PREFIX%\lib\site-packages\pip\_internal\utils\misc.py", line 931, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: '%PREFIX%\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PSommer\\AppData\\Local
\\Temp\\pip-req-build-f335sbkh\\setup.py'"'"'; __file__='"'"'C:\\Users\\PSommer\\AppData\\Local\\Temp\\pip-req-build-f335sbkh\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.
read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PSommer\AppData\Local\Temp\pip-record-kxt509_m\install-record.txt' --si
ngle-version-externally-managed --compile Check the logs for full command output.
Traceback (most recent call last):
  File "D:\PhDs\Philipp_Sommer\Miniconda3\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\PhDs\Philipp_Sommer\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "D:\PhDs\Philipp_Sommer\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "D:\PhDs\Philipp_Sommer\Miniconda3\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "D:\PhDs\Philipp_Sommer\Miniconda3\lib\site-packages\conda_build\build.py", line 2343, in build_tree
    notest=notest,
  File "D:\PhDs\Philipp_Sommer\Miniconda3\lib\site-packages\conda_build\build.py", line 1458, in build
    windows.build(m, build_file, stats=build_stats, provision_only=provision_only)
  File "D:\PhDs\Philipp_Sommer\Miniconda3\lib\site-packages\conda_build\windows.py", line 294, in build
    check_call_env(cmd, cwd=m.config.work_dir, stats=stats, rewrite_stdout_env=rewrite_env)
  File "D:\PhDs\Philipp_Sommer\Miniconda3\lib\site-packages\conda_build\utils.py", line 397, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "D:\PhDs\Philipp_Sommer\Miniconda3\lib\site-packages\conda_build\utils.py", line 377, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['cmd.exe', '/d', '/c', 'conda_build.bat']' returned non-zero exit status 1.
```
</details>

**Comment by Chilipp** [comment]
Hmm, actually the C-compiler is just not installed on our windows server... I'll discuss with our IT apartment to install it and then retry the build. But if anyone successfully builds the recipe on his own windows machine, I would be okay with creating the PR before. 

Just, from my personal experience, it is often easier to debug the recipe on a local machine than on the CI services that are used within conda-forge. Therefore I would like to have it working before.

**Comment by Chilipp** [comment]
Alright! The package did build well on Windows and is also now available via

```
conda install -c chilipp -c conda-forge tesserocr
```

(only win-64, though). I created the PR at https://github.com/conda-forge/staged-recipes/pull/9734 and propose to continue any discussion their. I only included @sirfz and me as recipe maintainers at the moment. If anyone else would be willing to get responsible, just post a comment in the PR.

PS: I will remove the tesserocr packages from my anaconda channel when the PR is merged.

**Comment by Chilipp** [comment]
Closed by https://github.com/conda-forge/staged-recipes/pull/9734

**Comment by chamoulox** [comment]
Hello @Chilipp ,

It seems that no packages of tesserocr has been build yet for conda-forge.

**Comment by Chilipp** [comment]
Hmm, thanks for the info! Don't know about the reason. I just pushed an empty commit to the repository in order to trigger the CI build (https://github.com/conda-forge/tesserocr-feedstock/commit/6fbf1ae180a14c215900f80f3ba1cb2ce04b081d) hope that works

**Comment by chamoulox** [comment]
Yes it seems that it helps, Azure pipeline succeeds and there is packages here : https://anaconda.org/conda-forge/tesserocr/files

I still have no results for
```conda search tesserocr -c conda-forge``` but I hope it's just a question of time.
Thanks !

**Comment by Chilipp** [comment]
should be available now (https://anaconda.org/conda-forge/tesserocr). did you try again?

**Comment by chamoulox** [comment]
Yes I have it now, it just took some time. :+1:

**Comment by Chilipp** [comment]
Great! Thanks again for the info! 👍

**Comment by joseavegaa** [comment]
Hi! 

I opened #287 a few days ago. Is it possible to update the conda-forge recipe for the latest version? Otherwise, let me know to push a PR to update documentation on the recommended way to install on Windows.

Thanks!
