### ISSUE TITLE
AttributeError when calling SetImage() (python 3)

### ISSUE THREAD

**Issue by dtenenba** [sirfz/tesserocr#22]
In Python 3.5.2 (in an ipython console) I've copied the file eurotext.tif from this repository to my working directory. I get an error trying to work with that image:

```ipython
In [50]: from tesserocr import PyTessBaseAPI

In [51]: with PyTessBaseAPI as api:
    ...:     api.SetImageFile('eurotext.tif')
    ...:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-51-252118aec8ba> in <module>()
----> 1 with PyTessBaseAPI as api:
      2     api.SetImageFile('eurotext.tif')
      3

AttributeError: __exit__

```

Also trying to use it directly:

```
In [52]: tesseract = PyTessBaseAPI()

In [53]: tesseract.SetImage('eurotext.tif')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-53-661b17ef8a1f> in <module>()
----> 1 tesseract.SetImage('eurotext.tif')

tesserocr.pyx in tesserocr.PyTessBaseAPI.SetImage (tesserocr.cpp:13256)()

tesserocr.pyx in tesserocr._image_buffer (tesserocr.cpp:2916)()

tesserocr.pyx in tesserocr._image_buffer (tesserocr.cpp:2780)()

AttributeError: 'str' object has no attribute 'save'
```

I'm able to open the image in PIL so it's a valid image:

```
In [54]: from PIL import Image

In [55]: im = Image.open('eurotext.tif')

In [56]: im
Out[56]: <PIL.TiffImagePlugin.TiffImageFile image mode=1 size=1024x800 at 0x7F7E100BF5F8>

```

What's going on here? Thanks in advance.

Here's what I have installed if that's helpful.

```
Cython==0.25.1
dask==0.12.0
decorator==4.0.10
ipython==5.1.0
ipython-genutils==0.1.0
networkx==1.11
numpy==1.11.2
pexpect==4.2.1
pickleshare==0.7.4
Pillow==3.4.2
prompt-toolkit==1.0.9
ptyprocess==0.5.1
Pygments==2.1.3
scikit-image==0.12.3
scipy==0.18.1
simplegeneric==0.8.1
six==1.10.0
tesserocr==2.1.3
toolz==0.8.1
traitlets==4.3.1
wcwidth==0.1.7
```

Also I am able to run tesserocr's tests (`python3 setup.py test`) without any errors so I think tesserocr is installed ok.

**Comment by dtenenba** [comment]
Sorry, my bad, this takes an Image object not a filename.

**Comment by dtenenba** [comment]
Or rather, I should have been calling SetImageFile() instead of SetImage().

**Comment by sirfz** [comment]
FYI, the proper syntax to use the api as a context manager is:

```python
with PyTessBaseAPI() as api:
    # use the api instance
```
(Note the parenthesis missing in your code above)

Refer to the [README](https://github.com/sirfz/tesserocr/blob/v2.1.3/README.rst) for more examples.

**Comment by dtenenba** [comment]
Duh, thanks.

**Comment by dtenenba** [comment]
BTW those examples don't work in python3 without some tweaking (in particular parentheses needed around `print`.

**Comment by sirfz** [comment]
True, they're written for Python 2. Perhaps I'll update it to a Python 3 friendly version in a future release.

**Comment by dtenenba** [comment]
Another AttributeError issue running the following script:

```python
from PIL import Image
from tesserocr import PyTessBaseAPI, RIL

image = Image.open('tesseract/testing/phototest.tif')
print(image)
with PyTessBaseAPI() as api:
    api.SetImage(image)
```

The output is:

```
<PIL.TiffImagePlugin.TiffImageFile image mode=1 size=640x480 at 0x7F41D9CF14A8>
Traceback (most recent call last):
  File "getcomponentimages.py", line 7, in <module>
    api.SetImage(image)
  File "tesserocr.pyx", line 1515, in tesserocr.PyTessBaseAPI.SetImage (tesserocr.cpp:13256)
  File "tesserocr.pyx", line 301, in tesserocr._image_buffer (tesserocr.cpp:2916)
  File "tesserocr.pyx", line 302, in tesserocr._image_buffer (tesserocr.cpp:2811)
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 1698, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.5/dist-packages/PIL/TiffImagePlugin.py", line 1487, in _save
    offset = ifd.save(fp)
  File "/usr/local/lib/python3.5/dist-packages/PIL/TiffImagePlugin.py", line 758, in save
    entries.append((tag, typ, count, data.ljust(4, b"\0"), b""))
AttributeError: 'tuple' object has no attribute 'ljust'
```

Seems like this should work?

**Comment by dtenenba** [comment]
FYI, It does work if I replace

```python
api.SetImage(image)
```

with

```python
api.SetImageFile('tesseract/testing/phototest.tif')
```

**Comment by sirfz** [comment]
This error is taking place in the PIL module and not in tesserocr, not sure it's a bug or a problem with your environment though. Try upgrading the Pillow module (`pip install -U pillow`).

**Comment by dtenenba** [comment]
My Pillow package is already the latest version.

Yes, your code reproduces the error. I guess that is a minimal, self-contained (except for the image) snippet I can submit to the PIL repos.

Thanks...appreciate all your help.

**Comment by sirfz** [comment]
Weird, worked for me on v3.3.1. Glad to help :)

**Comment by dtenenba** [comment]
Thanks, reported it at https://github.com/python-pillow/Pillow/issues/2278
