### ISSUE TITLE
Problem with API

### ISSUE THREAD

**Issue by johnlockejrr** [sirfz/tesserocr#345]
I have eScriptorium with tesseract and tesserocr, everything ok but when I try to train a model I get some error on API:
(https://ub-mannheim.github.io/eScriptorium_Dokumentation/eScriptorium-with-tesseract-extension.html)

```
[2024-03-11 14:11:09,546: WARNING/ForkPoolWorker-6] ['combine_tessdata', '-l', '/home/tesseract/eScriptorium/app/media/models/9e01fc44/samaritan_trans.traineddata']
'tesserocr.PyTessBaseAPI' object has no attribute 'WriteLSTMFLineData'
Traceback (most recent call last):
  File "/home/tesseract/eScriptorium/app/apps/core/tasks.py", line 987, in train
    {"kraken": train_kraken,
  File "/home/tesseract/eScriptorium/app/apps/core/tasks.py", line 653, in train_tesseract
    api.WriteLSTMFLineData(filepath.with_suffix('').name, str(filepath.parent.resolve()), cutout,
AttributeError: 'tesserocr.PyTessBaseAPI' object has no attribute 'WriteLSTMFLineData'
[2024-03-11 14:11:12,308: INFO/ForkPoolWorker-6] Task core.tasks.train[98c14ca7-901f-4c06-8bdb-d6a64b3e40f6] succeeded in 4.229517752999527s: None
```
Is the object `WriteLSTMFLineData` discontinued? If so, whith version does still have it? Thank you!

**Comment by zdenop** [comment]
Why are you reporting your issue here and not at eScriptorium?

**Comment by johnlockejrr** [comment]
Escriptorium with tesseract is not public branch. Just asked you if that
function/module still exists in your code or not. Thanks anyway!
